-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 16:44:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `id_Utilisateur` INT NOT NULL,
  `utilisateur_type` VARCHAR(255) NULL,
  `utilisateur_nom` VARCHAR(255) NULL,
  `utilisateur_prenom` VARCHAR(255) NULL,
  `utilisateur_mail` VARCHAR(255) NULL,
  `utilisateur_login` VARCHAR(255) NULL,
  `utilisateur_motDePasse` VARCHAR(255) NULL,
  `utilisateur_dateDeNaissance` DATE NULL,
  PRIMARY KEY (`id_Utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commande` (
  `id_Commande` INT NOT NULL,
  `commande_date` DATE NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`id_Commande`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Commande_Utilisateur_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Commande_Utilisateur`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logement` (
  `id_Logement` INT NOT NULL,
  `logement_adresse` VARCHAR(255) NULL,
  `logement_codePostal` VARCHAR(255) NULL,
  `logement_ville` VARCHAR(255) NULL,
  `pays` VARCHAR(255) NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`id_Logement`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Logement_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Logement_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAQ` (
  `id_FAQ` INT NOT NULL,
  `faq_question` VARCHAR(255) NULL,
  `faq_reponse` VARCHAR(255) NULL,
  PRIMARY KEY (`id_FAQ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commander`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commander` (
  `id_Commande` INT NOT NULL,
  `id_Capteur/actionneur` INT NULL,
  `commander_quantite` INT NULL,
  PRIMARY KEY (`id_Commande`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeCapteur/actionneur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeCapteur/actionneur` (
  `id_Capteur/actionneur` INT NOT NULL,
  `capteur/actionneur_fonction` VARCHAR(255) NULL,
  `capteur/actionneur_stock` INT NULL,
  PRIMARY KEY (`id_Capteur/actionneur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piece` (
  `id_Piece` INT NOT NULL,
  `piece_nom` VARCHAR(255) NULL,
  `Logement_idLogement` INT NOT NULL,
  `Logement_Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`id_Piece`, `Logement_idLogement`, `Logement_Utilisateur_idUtilisateur`),
  INDEX `fk_Piece_Logement1_idx` (`Logement_idLogement` ASC, `Logement_Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Piece_Logement1`
    FOREIGN KEY (`Logement_idLogement` , `Logement_Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Logement` (`id_Logement` , `Utilisateur_idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cemac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cemac` (
  `id_Cemac` INT NOT NULL,
  `cemac_nom` VARCHAR(255) NULL,
  `Piece_idPiece` INT NOT NULL,
  PRIMARY KEY (`id_Cemac`, `Piece_idPiece`),
  INDEX `fk_Cemac_Piece1_idx` (`Piece_idPiece` ASC),
  CONSTRAINT `fk_Cemac_Piece1`
    FOREIGN KEY (`Piece_idPiece`)
    REFERENCES `mydb`.`Piece` (`id_Piece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Capteur/actionneur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Capteur/actionneur` (
  `id_Capteur/actionneur` INT NOT NULL,
  `capteur/actionneur_numero` INT NULL,
  `capteur/actionneur_type` VARCHAR(255) NULL,
  `capteur/actionneur_fonction` VARCHAR(255) NULL,
  `Cemac_idCemac` INT NOT NULL,
  PRIMARY KEY (`id_Capteur/actionneur`, `Cemac_idCemac`),
  INDEX `fk_Capteur/actionneur_Cemac1_idx` (`Cemac_idCemac` ASC),
  CONSTRAINT `fk_Capteur/actionneur_Cemac1`
    FOREIGN KEY (`Cemac_idCemac`)
    REFERENCES `mydb`.`Cemac` (`id_Cemac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Panne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Panne` (
  `id_Panne` INT NOT NULL,
  `idCapteur/actionneur` INT NULL,
  `panne_date` DATE NULL,
  `Capteur/actionneur_idCapteur/actionneur` INT NOT NULL,
  `Capteur/actionneur_Cemac_idCemac` INT NOT NULL,
  PRIMARY KEY (`id_Panne`, `Capteur/actionneur_idCapteur/actionneur`, `Capteur/actionneur_Cemac_idCemac`),
  INDEX `fk_Panne_Capteur/actionneur1_idx` (`Capteur/actionneur_idCapteur/actionneur` ASC, `Capteur/actionneur_Cemac_idCemac` ASC),
  CONSTRAINT `fk_Panne_Capteur/actionneur1`
    FOREIGN KEY (`Capteur/actionneur_idCapteur/actionneur` , `Capteur/actionneur_Cemac_idCemac`)
    REFERENCES `mydb`.`Capteur/actionneur` (`id_Capteur/actionneur` , `Cemac_idCemac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scenario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scenario` (
  `id_Scenario` INT NOT NULL,
  `idCapteur/actionneur` INT NULL,
  `scenario_dateDebut` DATE NULL,
  `scenario_dateFin` DATE NULL,
  `scenario_valeur` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id_Scenario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donnees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donnees` (
  `id_Donnees` INT NOT NULL,
  `donnees_temps` INT NULL,
  `donnees_valeur` DECIMAL(6,2) NULL,
  `Capteur/actionneur_idCapteur/actionneur` INT NOT NULL,
  `Capteur/actionneur_Cemac_idCemac` INT NOT NULL,
  PRIMARY KEY (`id_Donnees`, `Capteur/actionneur_idCapteur/actionneur`, `Capteur/actionneur_Cemac_idCemac`),
  INDEX `fk_Donnees_Capteur/actionneur1_idx` (`Capteur/actionneur_idCapteur/actionneur` ASC, `Capteur/actionneur_Cemac_idCemac` ASC),
  CONSTRAINT `fk_Donnees_Capteur/actionneur1`
    FOREIGN KEY (`Capteur/actionneur_idCapteur/actionneur` , `Capteur/actionneur_Cemac_idCemac`)
    REFERENCES `mydb`.`Capteur/actionneur` (`id_Capteur/actionneur` , `Cemac_idCemac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scenario_has_Capteur/actionneur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scenario_has_Capteur/actionneur` (
  `Scenario_idScenario` INT NOT NULL,
  `Capteur/actionneur_idCapteur/actionneur` INT NOT NULL,
  `Capteur/actionneur_Cemac_idCemac` INT NOT NULL,
  PRIMARY KEY (`Scenario_idScenario`, `Capteur/actionneur_idCapteur/actionneur`, `Capteur/actionneur_Cemac_idCemac`),
  INDEX `fk_Scenario_has_Capteur/actionneur_Capteur/actionneur1_idx` (`Capteur/actionneur_idCapteur/actionneur` ASC, `Capteur/actionneur_Cemac_idCemac` ASC),
  INDEX `fk_Scenario_has_Capteur/actionneur_Scenario1_idx` (`Scenario_idScenario` ASC),
  CONSTRAINT `fk_Scenario_has_Capteur/actionneur_Scenario1`
    FOREIGN KEY (`Scenario_idScenario`)
    REFERENCES `mydb`.`Scenario` (`id_Scenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scenario_has_Capteur/actionneur_Capteur/actionneur1`
    FOREIGN KEY (`Capteur/actionneur_idCapteur/actionneur` , `Capteur/actionneur_Cemac_idCemac`)
    REFERENCES `mydb`.`Capteur/actionneur` (`id_Capteur/actionneur` , `Cemac_idCemac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande_has_typeCapteur/actionneur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commande_has_typeCapteur/actionneur` (
  `Commande_idCommande` INT NOT NULL,
  `Commande_Utilisateur_idUtilisateur` INT NOT NULL,
  `typeCapteur/actionneur_idCapteur/actionneur` INT NOT NULL,
  `Commander_idCommande` INT NOT NULL,
  PRIMARY KEY (`Commande_idCommande`, `Commande_Utilisateur_idUtilisateur`, `typeCapteur/actionneur_idCapteur/actionneur`),
  INDEX `fk_Commande_has_typeCapteur/actionneur_typeCapteur/actionne_idx` (`typeCapteur/actionneur_idCapteur/actionneur` ASC),
  INDEX `fk_Commande_has_typeCapteur/actionneur_Commande1_idx` (`Commande_idCommande` ASC, `Commande_Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Commande_has_typeCapteur/actionneur_Commander1_idx` (`Commander_idCommande` ASC),
  CONSTRAINT `fk_Commande_has_typeCapteur/actionneur_Commande1`
    FOREIGN KEY (`Commande_idCommande` , `Commande_Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Commande` (`id_Commande` , `Utilisateur_idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_typeCapteur/actionneur_typeCapteur/actionneur1`
    FOREIGN KEY (`typeCapteur/actionneur_idCapteur/actionneur`)
    REFERENCES `mydb`.`TypeCapteur/actionneur` (`id_Capteur/actionneur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_typeCapteur/actionneur_Commander1`
    FOREIGN KEY (`Commander_idCommande`)
    REFERENCES `mydb`.`Commander` (`id_Commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
